events {
    worker_connections 1024;
}

http {
    # Mendaftarkan server internal Docker
    upstream auth { server auth-service:8000; }
    upstream report { server report-service:8000; }
    upstream verifikasi { server verification-service:8000; }
    upstream case { server case-service:8000; }

    server {
        listen 80;

        # 1. Routing ke Auth Service
        location /api/auth/ {
            proxy_pass http://auth;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        # 2. Routing ke Report Service
        location /api/laporan/ {
            proxy_pass http://report;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        # 3. Routing ke Verification Service
        location /api/verifikasi/ {
            proxy_pass http://verifikasi;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        # 4. Routing ke Case Service
        location /api/penanganan/ {
            proxy_pass http://case;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 5. Routing statis foto laporan (Report Service)
        location /storage/ {
            proxy_pass http://report;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
